### ISSUE TITLE
Upgrade @types/hast to 3

### ISSUE THREAD

**Issue by crutchcorn** [rehypejs/rehype-retext#11]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

When using these with other newer packages that use Hast 3, we get errors due to typing mismatches.

### Solution

Upgrade @types/hast to 3. I tried to do this myself, but ran into issues with TypeScript complaining about `this` bindings somehow.

### Alternatives

While I'm experienced with TS and such, I feel like I'm lacking some context to fix this issues. If I could be helped a bit, I'd be happy to submit PRs across the ecosystem to help us all get upgraded :)

**Comment by wooorm** [comment]
Hey! Everything’s being released. But it takes time to go through 700+ packages.
This is also a types-only change, so you can ts-ignore/ts-expect-error and continue.
You can follow me or occasionally check https://github.com/wooorm to see where it’s currently at.

**Comment by wooorm** [comment]
done https://github.com/rehypejs/rehype-retext/releases/tag/4.0.0!
